### ISSUE TITLE
CREATE: RestAPI

### ISSUE THREAD

**Issue by AnteroKorvala** [AnteroKorvala/vinyl-shop-project#12]
### TO-DO

- [ ] GET: All items for feed
- [ ] GET: Wishlist
- [ ] INSERT: New User
- [ ] INSERT: Into Wishlist
- [ ] UPDATE: User Information
- [ ] UPDATE: Wishlist
**...**
